In [37]:
import requests
from datetime import datetime
from pathlib import Path
import os
import sys
import tomllib
import polars as pl

In [38]:
now = datetime.now()

CURRENT_NOTEBOOK_DIR = Path(os.getcwd())   # workspace/seoul_subway/src/notebooks

# Path.parents[0] == src
# Path.parents[1] == seoul_subway
# Path.parents[2] == workspace
ROOT_DIR = CURRENT_NOTEBOOK_DIR.parents[1]

ROOT_DIR

PosixPath('/Users/hongtaegyeong/workspace/seoul_subway')

In [39]:
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))


from src.ods.seoul_openapi_client import SeoulOpenApiClient

config_path = ROOT_DIR/"config"/"dev.toml"
with open(config_path, "rb") as f:  # (rb: 바이너리 모드 r: 텍스트 모드) 3.11+ tomllib을 사용한다면 무조건 rb로만 열여야 함
    config = tomllib.load(f)


API_KEY = config["seoul_api"]["global"]["api_key"]
SERVICE_NAME = config["seoul_api"]["services"]["subway_line"]
PAGE_SIZE = config["seoul_api"]["global"]["page_size"]


START_INDEX = 1

subway_api: SeoulOpenApiClient = SeoulOpenApiClient(API_KEY)
raw_date:dict = subway_api.fetch_data(
    service_name = SERVICE_NAME,
    start_idx= START_INDEX,
    end_idx= PAGE_SIZE
)

In [44]:
subway_rows = raw_date.get("SearchSTNBySubwayLineInfo").get("row")

print(len(subway_rows))

799

In [43]:
df = pl.DataFrame(subway_rows)
df

shape: (799, 7)
┌────────────┬──────────────┬────────────────┬──────────┬─────────┬────────────────┬───────────────┐
│ STATION_CD ┆ STATION_NM   ┆ STATION_NM_ENG ┆ LINE_NUM ┆ FR_CODE ┆ STATION_NM_CHN ┆ STATION_NM_JP │
│ ---        ┆ ---          ┆ ---            ┆ ---      ┆ ---     ┆ ---            ┆ N             │
│ str        ┆ str          ┆ str            ┆ str      ┆ str     ┆ str            ┆ ---           │
│            ┆              ┆                ┆          ┆         ┆                ┆ str           │
╞════════════╪══════════════╪════════════════╪══════════╪═════════╪════════════════╪═══════════════╡
│ 0153       ┆ 종로3가      ┆ Jongno         ┆ 01호선   ┆ 130     ┆ 钟路三街       ┆ チョンノサム  │
│            ┆              ┆ 3(sam)-ga      ┆          ┆         ┆                ┆ ガ            │
│ 1004       ┆ 노량진       ┆ Noryangjin     ┆ 01호선   ┆ 136     ┆ 鹭梁津         ┆ ノリャンジン  │
│ 1032       ┆ 신길         ┆ Singil         ┆ 01호선   ┆ 138     ┆ 新吉           ┆ シンギル      │
│ 1917       ┆ 청산         ┆ Cheongsan      ┆ 01호선   ┆ 100-1   ┆ 青山           ┆ チョンサン    │
│ 1005       ┆ 대방         ┆ Daebang        ┆ 01호선   ┆ 137     ┆ 大方           ┆ テバン        │
│ …          ┆ …            ┆ …              ┆ …        ┆ …       ┆ …              ┆ …             │
│ 3108       ┆ 신검단중앙   ┆ Singeomdanjung ┆ 인천선   ┆ I108    ┆ 新黔丹中央     ┆ シンゴムダン  │
│            ┆              ┆ ang            ┆          ┆         ┆                ┆ ジュンアン    │
│ 3107       ┆ 검단호수공원 ┆ Geomdan Lake   ┆ 인천선   ┆ I107    ┆ 黔丹湖水公園   ┆ コムダンホス  │
│            ┆              ┆ Park           ┆          ┆         ┆                ┆ ゴンウォン    │
│ 3129       ┆ 신연수       ┆ Sinyeonsu      ┆ 인천선   ┆ I129    ┆ 新延寿         ┆ シニョンス    │
│ 3114       ┆ 계산         ┆ Gyesan         ┆ 인천선   ┆ I114    ┆ 桂山           ┆ ケサン        │
│ 3134       ┆ 테크노파크   ┆ Technopark     ┆ 인천선   ┆ I134    ┆ 科技园         ┆ テクノパーク  │
└────────────┴──────────────┴────────────────┴──────────┴─────────┴────────────────┴───────────────┘

In [45]:
output_path = ROOT_DIR/"data_lake"/"seoul_subway"/"seoul_staion_info.parquet"

In [49]:
df.write_parquet(output_path)
if output_path.exists():
    print(f"{output_path} 파일 생성 완료")
else:
    print("경로: 파일 생성에 실패한 것 같습니다.")

/Users/hongtaegyeong/workspace/seoul_subway/data_lake/seoul_subway/seoul_staion_info.parquet 파일 생성 완료

In [52]:
df_read = pl.read_parquet(output_path)

df_read.head(5)

shape: (5, 7)
┌────────────┬────────────┬─────────────────┬──────────┬─────────┬────────────────┬────────────────┐
│ STATION_CD ┆ STATION_NM ┆ STATION_NM_ENG  ┆ LINE_NUM ┆ FR_CODE ┆ STATION_NM_CHN ┆ STATION_NM_JPN │
│ ---        ┆ ---        ┆ ---             ┆ ---      ┆ ---     ┆ ---            ┆ ---            │
│ str        ┆ str        ┆ str             ┆ str      ┆ str     ┆ str            ┆ str            │
╞════════════╪════════════╪═════════════════╪══════════╪═════════╪════════════════╪════════════════╡
│ 0153       ┆ 종로3가    ┆ Jongno          ┆ 01호선   ┆ 130     ┆ 钟路三街       ┆ チョンノサムガ │
│            ┆            ┆ 3(sam)-ga       ┆          ┆         ┆                ┆                │
│ 1004       ┆ 노량진     ┆ Noryangjin      ┆ 01호선   ┆ 136     ┆ 鹭梁津         ┆ ノリャンジン   │
│ 1032       ┆ 신길       ┆ Singil          ┆ 01호선   ┆ 138     ┆ 新吉           ┆ シンギル       │
│ 1917       ┆ 청산       ┆ Cheongsan       ┆ 01호선   ┆ 100-1   ┆ 青山           ┆ チョンサン     │
│ 1005       ┆ 대방       ┆ Daebang         ┆ 01호선   ┆ 137     ┆ 大方           ┆ テバン         │
└────────────┴────────────┴─────────────────┴──────────┴─────────┴────────────────┴────────────────┘

In [53]:
df_read.glimpse()

Rows: 799
Columns: 7
$ STATION_CD     <str> '0153', '1004', '1032', '1917', '1005', '1916', '0151', '0150', '1912', '1915'
$ STATION_NM     <str> '종로3가', '노량진', '신길', '청산', '대방', '소요산', '시청', '서울역', '지행', '동두천'
$ STATION_NM_ENG <str> 'Jongno 3(sam)-ga', 'Noryangjin', 'Singil', 'Cheongsan', 'Daebang', 'Soyosan', 'City Hall', 'Seoul Station', 'Jihaeng', 'Dongducheon'
$ LINE_NUM       <str> '01호선', '01호선', '01호선', '01호선', '01호선', '01호선', '01호선', '01호선', '01호선', '01호선'
$ FR_CODE        <str> '130', '136', '138', '100-1', '137', '100', '132', '133', '104', '101'
$ STATION_NM_CHN <str> '钟路三街', '鹭梁津', '新吉', '青山', '大方', '逍遥山', '市厅', '首尔', '纸杏', '东豆川'
$ STATION_NM_JPN <str> 'チョンノサムガ', 'ノリャンジン', 'シンギル', 'チョンサン', 'テバン', 'ソヨサン', 'シチョン', 'ソウル', 'チヘン', 'トンドゥチョン'

In [56]:
df_ods_subway = df_read.select([
    pl.col("STATION_CD").cast(pl.String).alias("station_id"),
    pl.col("STATION_NM").cast(pl.String).alias("station_name"),
    pl.col("LINE_NUM").cast(pl.String).alias("line_number")
])

print(df_ods_subway.shape)
print(df_ods_subway.schema)
print(df_ods_subway.glimpse())

(799, 3)
Schema({'station_id': String, 'station_name': String, 'line_number': String})
Rows: 799
Columns: 3
$ station_id   <str> '0153', '1004', '1032', '1917', '1005', '1916', '0151', '0150', '1912', '1915'
$ station_name <str> '종로3가', '노량진', '신길', '청산', '대방', '소요산', '시청', '서울역', '지행', '동두천'
$ line_number  <str> '01호선', '01호선', '01호선', '01호선', '01호선', '01호선', '01호선', '01호선', '01호선', '01호선'

None

In [57]:
from src.common.db_connectors import PostgresDBConnector

In [60]:
print(config)
db_config = config["database"]

db_connector = PostgresDBConnector(db_config)

db_url = db_connector.get_connection_url()
print("🔥 생성된 표준 DB URL:", db_url)

{'seoul_api': {'global': {'base_url': 'http://openapi.seoul.go.kr:8088', 'api_key': '7656714c4567757336356769446c6b', 'page_size': 1000}, 'services': {'elevator': 'tbTraficElvtr', 'subway_line': 'SearchSTNBySubwayLineInfo'}}, 'database': {'db_type': 'postgres', 'user': 'krx', 'password': 'krx', 'host': '192.168.56.10', 'port': 5432, 'database_name': 'bdp_test'}}
🔥 생성된 표준 DB URL: postgresql://krx:krx@192.168.56.10:5432/bdp_test